[package]
name = "advent_of_code"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.7.0"
itertools = "0.10.5"
num-integer = "0.1.44"
ndarray = "0.15.4"
crossterm = "0.19.0"
